### ISSUE TITLE
makes roles/letsencrypt-ansible the root of the repository

### ISSUE THREAD

**Issue by drzraf** [felixfontein/letsencrypt-ansible#2]
So that not only it can be cloned using ansible-galaxy, but using `git clone` too
thx

**Comment by felixfontein** [comment]
I'm not sure whether this is a good idea, since this is not a role you can use (with setting the correct variables), but a role you *MUST* edit first.

**Comment by felixfontein** [comment]
Now that the "MUST edit" part is dropped (at least for using challenge files), I guess we can do this as soon as #8 is merged.
