### ISSUE TITLE
role more path-independant

### ISSUE THREAD

**Issue by drzraf** [felixfontein/letsencrypt-ansible#4]
$ cd roles
$ git clone felixfontein/letsencrypt-ansible
$ cd felixfontein/letsencrypt-ansible
$ git mv role/ansible/* ./
 # do the change to `tasks/issue-certs-copy.yml` and `tasks/issue-certs-cleanup.yml`
=> This won't work,
* because pwd is set the playbooks/ so construct like `roles/letsencrypt/code/acme_compact.py` only works if roles are below the `playbooks/` directory, but not if there `roles` is a sibling directory of `playbooks/`. In such case ../roles/felixfontein.letsencrypt-ansible/code/acme_compact.py should be used

Even in the default case where the role is kept in the original directory, this won't work because pwd is still `playbooks/` which does not contains a `roles/ansible/` directory.

The same happens to the keys/ and, more importantly to the scratch/, created under `playbooks/` but then used inside `copy` directives which will search inside the role-specific `files/` directory (and won't find them)

**Comment by drzraf** [comment]
using [role_path](https://github.com/ansible/ansible/commit/7051cdeb57d947a213803ca28a4e1a6a2f905d26) (>= 1.8) should do the trick (https://docs.ansible.com/ansible/playbooks_variables.html)

**Comment by felixfontein** [comment]
That's a great idea. I also made `keys/` and `scratch/` configurable (with current values set as defaults).
