### ISSUE TITLE
adapt to whether we are root or not

### ISSUE THREAD

**Issue by drzraf** [felixfontein/letsencrypt-ansible#6]
local_action respect the `become` option.
`ansible -s` or `become: yes` inside the role. In such a case local files created belong to root.
For that reason it may be interesting to not create these files as root (although it's the developer machine).
But using become=no is not an option because the only task run on the server needs a root privilege.
`owner=root group=http` in `tasks/issue-certs-copy.yml`.

Since it's a file that is expected to be modified, at least this trick could be documented.

**Comment by felixfontein** [comment]
Well, the task in `tasks/issue-certs-copy.yml` is an example. It really depends on how your server environment looks like / works. I could remove the `owner=root group=http` and change the access rights to 0755 / 0644 in the example. It doesn't really matter in the end; you (as an admin) must know how your infrastructure looks like before you can adjust this task.
